{
 "title": "ETH2 Staking Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": "label_values(crypto_currency, pair)"
   },
   { "name": "validator_launchpad", "query": "localhost:8081" },
   { "name": "validator_ethdo", "query": "localhost:8079" }
  ]
 },
 "panels": [
  {
   "title": "Hourly",
   "type": "stat",
   "description": "This panel shows the earning during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)/(avg_over_time(count(validator_balance > 16)[1h:30s])*32/24/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)/(avg_over_time(count(validator_balance > 16)[1d:12m])*32/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "stat",
   "description": "This panel shows the earning during the last month, and the annualized % of the monthly earning.\n\nThose data won't be shown until the first validator is at least one month old, or that you started prometheus at least one month ago. Ensure to run Prometheus with the flag `--storage.tsdb.retention.time=31d` if you want this panel to get enough data\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)/(avg_over_time(count(validator_balance > 16)[30d:6h])*32/12)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total $",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*100/(count(validator_balance > 16 and validator_statuses == 3)*32)",
     "legendFormat": "ROI"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"beacon node\"}/32) - beacon_finalized_epoch{job=\"beacon node\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Slot delay",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Warnings & Errors over the past 24 hours.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[24h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[24h]) > 0)",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$validator_job\", level=\"warning\"}[24h]) > 0)"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$validator_job\", level=\"error\"}[24h]) > 0)"
    }
   ]
  },
  {
   "title": "Validator",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600",
     "legendFormat": "launchpad"
    }
   ]
  },
  {
   "title": "Node time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester*100"
    },
    {
     "expr": "(beacon_prev_epoch_target_gwei / beacon_prev_epoch_active_gwei)*100"
    },
    {
     "expr": "(beacon_previous_live_validators/beacon_previous_active_validators)*100"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"beacon node\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Inclusion Freq.",
   "type": "stat",
   "description": "Average inclusion distance of the last attestations by all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(validator_inclusion_distance)"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon node\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"beacon node\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  { "title": "Time until Activation", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 } },
  {
   "title": "Validator main info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Network Par. Rate",
   "type": "stat",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"beacon node\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"beacon node\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"beacon node\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Validator(s) balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    { "expr": "sum(validator_balance > 16)", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table-old",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node_exporter\"})-sum(node_filesystem_avail_bytes{job=\"node_exporter\"}))/sum(node_filesystem_size_bytes{job=\"node_exporter\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - node_memory_Buffers_bytes{job=\"node_exporter\"} - node_memory_Cached_bytes{job=\"node_exporter\"} - node_memory_SwapCached_bytes{job=\"node_exporter\"} - node_memory_Slab_bytes{job=\"node_exporter\"} - node_memory_PageTables_bytes{job=\"node_exporter\"} - node_memory_VmallocUsed_bytes{job=\"node_exporter\"} ) or ( node_memory_MemTotal{job=\"node_exporter\"} - node_memory_MemFree{job=\"node_exporter\"} - node_memory_Buffers{job=\"node_exporter\"} - node_memory_Cached{job=\"node_exporter\"} - node_memory_SwapCached{job=\"node_exporter\"} - node_memory_Slab{job=\"node_exporter\"} - node_memory_PageTables{job=\"node_exporter\"} - node_memory_VmallocUsed{job=\"node_exporter\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node_exporter\"} or node_memory_Buffers{job=\"node_exporter\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter\"} or node_memory_Cached{job=\"node_exporter\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"} or node_memory_MemFree{job=\"node_exporter\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node_exporter\"} or node_memory_Slab{job=\"node_exporter\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"node_exporter\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"node_exporter\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$node_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$validator_job\"}[1m:5s])",
     "legendFormat": "memory {{job}} {{instance}}"
    },
    {
     "expr": "((process_cpu_seconds_total{job=\"$node_job\"} - process_cpu_seconds_total{job=\"$node_job\"} offset 2m) > 0)*100/120/go_maxprocs{job=\"$node_job\"}",
     "legendFormat": "CPU {{job}}"
    },
    {
     "expr": "((process_cpu_seconds_total{job=\"$validator_job\"} - process_cpu_seconds_total{job=\"$validator_job\"} offset 2m) > 0)*100/120/go_maxprocs{job=\"$validator_job\"}",
     "legendFormat": "CPU {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0) ",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{job=\"validator\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  }
 ]
}